server:
  port: 8081
  error:
    include-message: always
    include-stacktrace: never

spring:
  application:
    name: hexagonal
  datasource:
    url: jdbc:h2:mem:hexagonal-db;DB_CLOSE_DELAY=-1
    username: h2
    password: h2
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true